function clean(value=''){return String(value??'').replace(/[<>]/g,'').trim().slice(0,4000);}
function oneLine(value=''){return clean(value).replace(/[\r\n\t]+/g,' ').replace(/\s{2,}/g,' ').slice(0,250);}
function md(value=''){return clean(value).replace(/([\[\]()*_`#!>|])/g,'\\$1');}
function mdOne(value=''){return md(oneLine(value));}
function isEmail(value=''){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(value).trim());}
function slug(value=''){return oneLine(value).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)||'unknown';}
function priority(score='',tier=''){const n=Number(score||0),t=String(tier).toLowerCase();if(t.includes('hot')||n>=80)return'priority-hot';if(t.includes('booking'))return'priority-booking';if(t.includes('audit')||n>=62)return'priority-audit';if(n>=42)return'priority-training';return'priority-foundation';}
function requestKind(data={}){return oneLine(data.request_type||data.form_name||data['form-name']||'Lead request');}
function submissionId(data={}){const id=oneLine(data.submission_id).slice(0,80);return /^[A-Za-z0-9._:-]{8,80}$/.test(id)?id:'';}
function issueBody(data){const sid=submissionId(data);return `# AI Kollege Lead\n\n## Request\n- Type: ${mdOne(requestKind(data))}\n- Received: ${new Date().toISOString()}\n- Submission ID: ${sid||'not supplied'}\n\n## Contact\n- Name: ${mdOne(data.name)}\n- Email: ${mdOne(data.email)}\n- Phone: ${mdOne(data.phone).slice(0,80)}\n\n## Details\n- Selected path: ${mdOne(data.path)}\n- Recommended path: ${mdOne(data.recommended_path)}\n- Lead tier: ${mdOne(data.lead_tier)}\n- Readiness score: ${mdOne(data.readiness_score)}\n- Score summary: ${md(data.score_summary)}\n- Audience type: ${mdOne(data.audience_type)}\n- Timeline: ${mdOne(data.timeline)}\n- Budget range: ${mdOne(data.budget_range)}\n- Meeting length: ${mdOne(data.meeting_length||data.call_length)}\n- Meeting preference: ${mdOne(data.meeting_preference||data.meeting_type)}\n- Timezone: ${mdOne(data.timezone)}\n- Preferred time 1: ${mdOne(data.preferred_time_1||[data.preferred_date_1,data.preferred_time_window_1].filter(Boolean).join(' '))}\n- Preferred time 2: ${mdOne(data.preferred_time_2||[data.preferred_date_2,data.preferred_time_window_2].filter(Boolean).join(' '))}\n- Preferred time 3: ${mdOne(data.preferred_time_3)}\n\n## Message\n${md(data.message)}\n\n## Source\n- Landing page: ${md(data.landing_page).slice(0,1000)}\n- Referrer: ${md(data.referrer).slice(0,1000)}\n- UTM source: ${mdOne(data.utm_source)}\n- UTM medium: ${mdOne(data.utm_medium)}\n- UTM campaign: ${mdOne(data.utm_campaign)}\n- UTM term: ${mdOne(data.utm_term)}\n- UTM content: ${mdOne(data.utm_content)}\n\nPrivate customer record. Do not copy into public issues, discussions, or logs.\n`;}
async function postIssue(owner,repoName,headers,title,body,labels){return fetch(`https://api.github.com/repos/${owner}/${repoName}/issues`,{method:'POST',headers,body:JSON.stringify(labels?{title,body,labels}:{title,body})});}
async function readRequestData(req){const contentType=req.headers.get('content-type')||'';if(contentType.includes('application/json'))return await req.json();return Object.fromEntries((await req.formData()).entries());}
async function verifyPrivateRepo(owner,repoName,headers){const r=await fetch(`https://api.github.com/repos/${owner}/${repoName}`,{headers});if(!r.ok)return false;const meta=await r.json();return meta?.private===true;}
async function findDuplicate(owner,repoName,headers,id){if(!id)return null;try{const q=encodeURIComponent(`repo:${owner}/${repoName} is:issue in:body "Submission ID: ${id}"`);const r=await fetch(`https://api.github.com/search/issues?q=${q}&per_page=1`,{headers});if(!r.ok)return null;const data=await r.json();const item=data.items?.[0];return item?{issue_url:item.html_url,issue_number:item.number}:null;}catch{return null;}}
async function createIssue(data){const secret=process.env.LEADS_SECRET,repo=process.env.LEADS_REPO;if(!secret||!repo||!repo.includes('/'))return{ok:false,status:503,error:'not_configured'};const[owner,repoName]=repo.split('/');const headers={Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'ai-kollege-lead-capture'};headers[['Author','ization'].join('')]=['Bearer',secret].join(' ');if(!(await verifyPrivateRepo(owner,repoName,headers)))return{ok:false,status:503,error:'unsafe_lead_repository'};const sid=submissionId(data),duplicate=await findDuplicate(owner,repoName,headers,sid);if(duplicate)return{ok:true,duplicate:true,...duplicate};const kind=requestKind(data),titlePrefix=kind.toLowerCase().includes('booking')?'[Booking]':'[Lead]',title=`${titlePrefix} ${oneLine(data.name)||'Unknown'} — ${oneLine(data.path||data.recommended_path)||'AI Kollege'}`.slice(0,250),body=issueBody(data),labels=['lead','ai-readiness-pass',priority(data.readiness_score,data.lead_tier),`path-${slug(data.path||data.recommended_path)}`,`audience-${slug(data.audience_type||kind)}`];let response=await postIssue(owner,repoName,headers,title,body,labels);if(!response.ok&&[400,422].includes(response.status))response=await postIssue(owner,repoName,headers,title,body,null);if(!response.ok)return{ok:false,status:response.status,error:'issue_create_failed'};const issue=await response.json();return{ok:true,duplicate:false,issue_url:issue.html_url,issue_number:issue.number};}
const rlBuckets=new Map();function throttle(key,limit=6,windowMs=60000){const now=Date.now(),hits=(rlBuckets.get(key)||[]).filter(t=>now-t<windowMs);if(hits.length>=limit){rlBuckets.set(key,hits);return false;}hits.push(now);rlBuckets.set(key,hits);return true;}
export default async(req,context)=>{if(req.method!=='POST')return Response.json({ok:false,error:'method_not_allowed'},{status:405});const contentLength=Number(req.headers.get('content-length')||0);if(contentLength>100000)return Response.json({ok:false,error:'request_too_large'},{status:413});const ip=(context?.ip||req.headers.get('x-forwarded-for')||'unknown').split(',')[0].trim();if(!throttle(`lead:${ip}`))return Response.json({ok:false,fallback:'email_form',error:'rate_limited'},{status:429});let data;try{data=await readRequestData(req);}catch{return Response.json({ok:false,error:'invalid_request_body'},{status:400});}if(clean(data._gotcha||data._honey))return Response.json({ok:true,ignored:true});if(!oneLine(data.name)||!isEmail(data.email))return Response.json({ok:false,error:'name_and_email_required'},{status:400});try{const result=await createIssue(data);if(!result.ok)return Response.json({ok:false,fallback:'email_form',error:result.error},{status:result.status||500});return Response.json({ok:true,...result});}catch{return Response.json({ok:false,fallback:'email_form',error:'lead_tracker_failed'},{status:500});}};
export const config={path:'/.netlify/functions/capture-lead',rateLimit:{windowLimit:12,windowSize:60,aggregateBy:['ip','domain']}};
