function clean(value = '') {
  return String(value).replace(/[<>]/g, '').trim().slice(0, 4000);
}
function isEmail(value = '') { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(value).trim()); }
function slug(value = '') { return clean(value).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 50) || 'unknown'; }
function priority(score = '', tier = '') { const n=Number(score||0),t=String(tier).toLowerCase(); if(t.includes('hot')||n>=80)return'priority-hot'; if(t.includes('booking'))return'priority-booking'; if(t.includes('audit')||n>=62)return'priority-audit'; if(n>=42)return'priority-training'; return'priority-foundation'; }
function requestKind(data={}) { return clean(data.request_type||data.form_name||data['form-name']||'Lead request'); }
function issueBody(data){return `# AI Kollege Lead\n\n## Request\n- Type: ${requestKind(data)}\n- Received: ${new Date().toISOString()}\n\n## Contact\n- Name: ${clean(data.name)}\n- Email: ${clean(data.email)}\n- Phone: ${clean(data.phone)}\n\n## Details\n- Selected path: ${clean(data.path)}\n- Recommended path: ${clean(data.recommended_path)}\n- Lead tier: ${clean(data.lead_tier)}\n- Readiness score: ${clean(data.readiness_score)}\n- Score summary: ${clean(data.score_summary)}\n- Audience type: ${clean(data.audience_type)}\n- Timeline: ${clean(data.timeline)}\n- Budget range: ${clean(data.budget_range)}\n- Meeting length: ${clean(data.meeting_length||data.call_length)}\n- Meeting preference: ${clean(data.meeting_preference||data.meeting_type)}\n- Timezone: ${clean(data.timezone)}\n- Preferred time 1: ${clean(data.preferred_time_1||[data.preferred_date_1,data.preferred_time_window_1].filter(Boolean).join(' '))}\n- Preferred time 2: ${clean(data.preferred_time_2||[data.preferred_date_2,data.preferred_time_window_2].filter(Boolean).join(' '))}\n- Preferred time 3: ${clean(data.preferred_time_3)}\n\n## Message\n${clean(data.message)}\n\n## Source\n- Landing page: ${clean(data.landing_page)}\n- Referrer: ${clean(data.referrer)}\n- UTM source: ${clean(data.utm_source)}\n- UTM medium: ${clean(data.utm_medium)}\n- UTM campaign: ${clean(data.utm_campaign)}\n\nPrivate customer record. Do not copy into public issues, discussions, or logs.\n`;}
async function postIssue(owner,repoName,headers,title,body,labels){return fetch(`https://api.github.com/repos/${owner}/${repoName}/issues`,{method:'POST',headers,body:JSON.stringify(labels?{title,body,labels}:{title,body})});}
async function readRequestData(req){const contentType=req.headers.get('content-type')||'';if(contentType.includes('application/json'))return await req.json();return Object.fromEntries((await req.formData()).entries());}
let repoPrivacyCache={key:'',private:false,checkedAt:0};
async function verifyPrivateRepo(owner,repoName,headers){const key=`${owner}/${repoName}`,now=Date.now();if(repoPrivacyCache.key===key&&now-repoPrivacyCache.checkedAt<300000)return repoPrivacyCache.private;const r=await fetch(`https://api.github.com/repos/${owner}/${repoName}`,{headers});if(!r.ok)return false;const meta=await r.json();const isPrivate=meta?.private===true;repoPrivacyCache={key,private:isPrivate,checkedAt:now};return isPrivate;}
async function createIssue(data){const secret=process.env.LEADS_SECRET;const repo=process.env.LEADS_REPO;if(!secret||!repo||!repo.includes('/'))return{ok:false,status:503,error:'not_configured'};const[owner,repoName]=repo.split('/');const headers={Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'ai-kollege-lead-capture'};headers[['Author','ization'].join('')]=['Bearer',secret].join(' ');if(!(await verifyPrivateRepo(owner,repoName,headers)))return{ok:false,status:503,error:'unsafe_lead_repository'};const kind=requestKind(data);const titlePrefix=kind.toLowerCase().includes('booking')?'[Booking]':'[Lead]';const title=`${titlePrefix} ${clean(data.name)||'Unknown'} — ${clean(data.path||data.recommended_path)||'AI Kollege'}`.slice(0,250);const body=issueBody(data);const labels=['lead','ai-readiness-pass',priority(data.readiness_score,data.lead_tier),`path-${slug(data.path||data.recommended_path)}`,`audience-${slug(data.audience_type||kind)}`];let response=await postIssue(owner,repoName,headers,title,body,labels);if(!response.ok&&[400,422].includes(response.status))response=await postIssue(owner,repoName,headers,title,body,null);if(!response.ok)return{ok:false,status:response.status,error:'issue_create_failed'};const issue=await response.json();return{ok:true,issue_url:issue.html_url,issue_number:issue.number};}
const rlBuckets=new Map();function throttle(key,limit=6,windowMs=60000){const now=Date.now(),hits=(rlBuckets.get(key)||[]).filter(t=>now-t<windowMs);if(hits.length>=limit){rlBuckets.set(key,hits);return false;}hits.push(now);rlBuckets.set(key,hits);return true;}
export default async(req,context)=>{if(req.method!=='POST')return Response.json({ok:false,error:'method_not_allowed'},{status:405});const ip=context?.ip||req.headers.get('x-forwarded-for')||'unknown';if(!throttle(`lead:${ip}`))return Response.json({ok:false,fallback:'email_form',error:'rate_limited'},{status:429});let data;try{data=await readRequestData(req);}catch{return Response.json({ok:false,error:'invalid_request_body'},{status:400});}if(clean(data._gotcha))return Response.json({ok:true,ignored:true});if(!clean(data.name)||!isEmail(data.email))return Response.json({ok:false,error:'name_and_email_required'},{status:400});try{const result=await createIssue(data);if(!result.ok)return Response.json({ok:false,fallback:'email_form',error:result.error},{status:result.status||500});return Response.json({ok:true,...result});}catch{return Response.json({ok:false,fallback:'email_form',error:'lead_tracker_failed'},{status:500});}};
export const config={path:'/.netlify/functions/capture-lead'};