import test from 'node:test';
import assert from 'node:assert/strict';
import {checkOwnerToken,isAssistantConfigured,handleAssistantAction,fetchTodaysBookings,ownerToday,suggestBusinessLinks,BUSINESS_LINKS} from '../lib/assistant-core.mjs';
const realFetch=globalThis.fetch;
function fakeClient(text='ok'){return{messages:{create:async()=>({stop_reason:'end_turn',content:[{type:'text',text}]})}};}
const SAMPLE_ISSUES=[{number:12,title:'[Booking] Test Person — Business AI Readiness Audit',html_url:'https://github.com/example/repo/issues/12',labels:[{name:'lead'},{name:'booking'}],created_at:'2026-07-20T12:00:00Z',body:'Name: Test Person\nEmail: test@example.com\nPreferred time 1: Tuesday 10 AM'},{number:11,title:'Training lead — AI Starter Pass',html_url:'https://github.com/example/repo/issues/11',labels:[{name:'lead'}],created_at:'2026-07-20T11:00:00Z',body:'Name: Other Person\nEmail: other@example.com'}];
function setLeadEnv(repo=`x/private-${Math.random().toString(36).slice(2)}`){process.env.LEADS_SECRET='t';process.env.LEADS_REPO=repo;return repo;}
function privateRepoFetch(repo,{issues=SAMPLE_ISSUES,issue=SAMPLE_ISSUES[0],calendarText=null}={}){return async(url)=>{const s=String(url);if(s===`https://api.github.com/repos/${repo}`)return new Response(JSON.stringify({private:true}),{status:200});if(s.includes('calendar.google.com'))return new Response(calendarText||'',{status:200});if(/\/issues\/\d+$/.test(s))return new Response(JSON.stringify(issue),{status:200});return new Response(JSON.stringify(issues),{status:200});};}
function cleanup(){globalThis.fetch=realFetch;for(const key of ['LEADS_SECRET','LEADS_REPO','OWNER_ASSISTANT_TOKEN','ANTHROPIC_API_KEY','CALENDAR_TIMEZONE','GOOGLE_CALENDAR_ICS_URL'])delete process.env[key];}

test('owner token check is required and constant-time safe on shape',()=>{process.env.OWNER_ASSISTANT_TOKEN='private-owner-token';assert.equal(checkOwnerToken('Bearer private-owner-token'),true);assert.equal(checkOwnerToken('Bearer wrong'),false);assert.equal(checkOwnerToken(''),false);cleanup();});
test('assistant is not configured without both API key and owner token',()=>{cleanup();assert.equal(isAssistantConfigured(),false);process.env.ANTHROPIC_API_KEY='sk-test';assert.equal(isAssistantConfigured(),false);process.env.OWNER_ASSISTANT_TOKEN='owner';assert.equal(isAssistantConfigured(),true);cleanup();});
test('business link catalog is internal and covers core customer journeys',()=>{const keys=new Set(BUSINESS_LINKS.map(x=>x.key));for(const key of ['home','score','courses','booking','answers','checklist','refunds','privacy'])assert.ok(keys.has(key));assert.equal(keys.has('buyer'),false);for(const link of BUSINESS_LINKS)assert.match(link.href,/^\//);});
test('link suggestions map business language to verified pages',()=>{const links=suggestBusinessLinks('Give me the booking link and refund page');const keys=links.map(x=>x.key);assert.ok(keys.includes('booking'));assert.ok(keys.includes('refunds'));});
test('purchase and checkout requests point to offers instead of success/onboarding URL',()=>{const links=suggestBusinessLinks('Where can a customer purchase or checkout?');assert.ok(links.some(x=>x.key==='courses'));assert.ok(links.every(x=>!x.href.includes('purchase-success')));});
test('direct link requests do not require customer data or model generation',async()=>{cleanup();let fetched=false;globalThis.fetch=async()=>{fetched=true;throw new Error('should not fetch');};const result=await handleAssistantAction({action:'ask',prompt:'Give me the booking link'},fakeClient('should not be used'));assert.equal(result.ok,true);assert.ok(result.links.some(x=>x.key==='booking'));assert.match(result.answer,/verified AI Kollege pages/i);assert.equal(fetched,false);cleanup();});
test('ordinary business questions do not pull private lead context unnecessarily',async()=>{cleanup();let fetched=false;globalThis.fetch=async()=>{fetched=true;throw new Error('should not fetch');};const result=await handleAssistantAction({action:'ask',prompt:'What is the safest way to explain our Starter Pass?'},fakeClient('Use concise truthful language.'));assert.equal(result.ok,true);assert.equal(result.answer,'Use concise truthful language.');assert.equal(fetched,false);cleanup();});
test('business_links returns the complete verified directory',async()=>{const result=await handleAssistantAction({action:'business_links'});assert.equal(result.ok,true);assert.equal(result.links.length,BUSINESS_LINKS.length);});
test('leads_summary reads private lead issues and returns a summary',async()=>{const repo=setLeadEnv();globalThis.fetch=privateRepoFetch(repo);const result=await handleAssistantAction({action:'leads_summary'},fakeClient('Lead summary'));assert.equal(result.ok,true);assert.equal(result.leads.length,2);assert.equal(result.summary,'Lead summary');cleanup();});
test('Owner Studio refuses public lead repository',async()=>{const repo=setLeadEnv();let issueRead=false;globalThis.fetch=async(url)=>{const s=String(url);if(s===`https://api.github.com/repos/${repo}`)return new Response(JSON.stringify({private:false}),{status:200});issueRead=true;return new Response(JSON.stringify(SAMPLE_ISSUES),{status:200});};const result=await handleAssistantAction({action:'leads_summary'},fakeClient());assert.equal(result.ok,false);assert.equal(result.error,'unsafe_lead_repository');assert.equal(issueRead,false);cleanup();});
test('pipeline health reports private lead store and calendar state without exposing secrets',async()=>{const repo=setLeadEnv();process.env.ANTHROPIC_API_KEY='sk';process.env.OWNER_ASSISTANT_TOKEN='owner';process.env.GOOGLE_CALENDAR_ICS_URL='https://calendar.google.com/private.ics';globalThis.fetch=privateRepoFetch(repo);const result=await handleAssistantAction({action:'pipeline_health'});assert.equal(result.ok,true);assert.equal(result.checks.lead_store,'private and reachable');assert.equal(result.checks.calendar,'configured');assert.equal(result.checks.owner_assistant,'configured');assert.equal(result.checks.public_routes,'configured in application');assert.ok(result.links.length>0);assert.doesNotMatch(JSON.stringify(result),/OWNER_ASSISTANT_TOKEN|LEADS_SECRET/);cleanup();});
test('draft_reply returns a draft, private lead link and useful page links without sending',async()=>{const repo=setLeadEnv();globalThis.fetch=privateRepoFetch(repo);const result=await handleAssistantAction({action:'draft_reply',issue_number:12},fakeClient('Draft reply'));assert.equal(result.ok,true);assert.equal(result.draft,'Draft reply');assert.match(result.note,/nothing has been sent/i);assert.ok(result.links.some(x=>x.href.includes('/issues/12')));cleanup();});
test('ownerToday returns the local calendar date in the configured timezone',()=>{const utc=new Date().toISOString().slice(0,10).replace(/-/g,''),ny=ownerToday('America/New_York');assert.match(ny,/^\d{8}$/);const kiritimati=ownerToday('Pacific/Kiritimati');assert.ok(kiritimati>=utc||Number(kiritimati)>=Number(ny));});
test('today action surfaces a lead-tracker error instead of reporting no bookings',async()=>{const repo=setLeadEnv();globalThis.fetch=async(url)=>String(url)===`https://api.github.com/repos/${repo}`?new Response('{"message":"Bad credentials"}',{status:401}):new Response('[]',{status:200});const result=await handleAssistantAction({action:'today'},fakeClient('unused'));assert.equal(result.ok,false);assert.match(result.error,/lead_tracker_error/);assert.match(result.note,/may be hidden/i);cleanup();});
test('today lists booking requests and parses today calendar events in owner timezone',async()=>{const repo=setLeadEnv();process.env.CALENDAR_TIMEZONE='America/New_York';process.env.GOOGLE_CALENDAR_ICS_URL='https://calendar.google.com/private.ics';const today=ownerToday(process.env.CALENDAR_TIMEZONE),calendarText=`BEGIN:VCALENDAR\nBEGIN:VEVENT\nDTSTART:${today}T1400\nSUMMARY:Fit review call\nEND:VEVENT\nBEGIN:VEVENT\nDTSTART:19990101T1000\nSUMMARY:Old event\nEND:VEVENT\nEND:VCALENDAR`;globalThis.fetch=privateRepoFetch(repo,{calendarText});const{booking_requests,calendar_events}=await fetchTodaysBookings();assert.equal(booking_requests.length,1);assert.match(booking_requests[0].title,/^\[Booking\]/);assert.equal(calendar_events.length,1);assert.equal(calendar_events[0].summary,'Fit review call');assert.equal(calendar_events[0].time,'14:00');cleanup();});
