import test from 'node:test';
import assert from 'node:assert/strict';
import {checkOwnerToken,isAssistantConfigured,handleAssistantAction,fetchTodaysBookings,ownerToday} from '../lib/assistant-core.mjs';
function fakeClient(text='ok'){return{messages:{create:async()=>({stop_reason:'end_turn',content:[{type:'text',text}]})}};}
const SAMPLE_ISSUES=[{number:12,title:'[Booking] Test Person — Business AI Readiness Audit',html_url:'https://github.com/example/repo/issues/12',labels:[{name:'lead'},{name:'booking'}],created_at:'2026-07-20T12:00:00Z',body:'Name: Test Person\nEmail: test@example.com\nPreferred time 1: Tuesday 10 AM'},{number:11,title:'Training lead — AI Starter Pass',html_url:'https://github.com/example/repo/issues/11',labels:[{name:'lead'}],created_at:'2026-07-20T11:00:00Z',body:'Name: Other Person\nEmail: other@example.com'}];
function setLeadEnv(repo=`x/private-${Math.random().toString(36).slice(2)}`){process.env.LEADS_SECRET='t';process.env.LEADS_REPO=repo;return repo;}
function privateRepoFetch(repo,{issues=SAMPLE_ISSUES,issue=SAMPLE_ISSUES[0],calendarText=null}={}){return async(url)=>{const s=String(url);if(s===`https://api.github.com/repos/${repo}`)return new Response(JSON.stringify({private:true}),{status:200});if(s.includes('calendar.google.com'))return new Response(calendarText||'',{status:200});if(/\/issues\/\d+$/.test(s))return new Response(JSON.stringify(issue),{status:200});return new Response(JSON.stringify(issues),{status:200});};}
function cleanup(){for(const key of ['LEADS_SECRET','LEADS_REPO','OWNER_ASSISTANT_TOKEN','ANTHROPIC_API_KEY','CALENDAR_TIMEZONE','GOOGLE_CALENDAR_ICS_URL'])delete process.env[key];}
test('owner token check is required and constant-time safe on shape',()=>{process.env.OWNER_ASSISTANT_TOKEN='private-owner-token';assert.equal(checkOwnerToken('Bearer private-owner-token'),true);assert.equal(checkOwnerToken('Bearer wrong'),false);assert.equal(checkOwnerToken(''),false);cleanup();});
test('assistant is not configured without both API key and owner token',()=>{cleanup();assert.equal(isAssistantConfigured(),false);process.env.ANTHROPIC_API_KEY='sk-test';assert.equal(isAssistantConfigured(),false);process.env.OWNER_ASSISTANT_TOKEN='owner';assert.equal(isAssistantConfigured(),true);cleanup();});
test('leads_summary reads private lead issues and returns a summary',async()=>{const repo=setLeadEnv();globalThis.fetch=privateRepoFetch(repo);const result=await handleAssistantAction({action:'leads_summary'},fakeClient('Lead summary'));assert.equal(result.ok,true);assert.equal(result.leads.length,2);assert.equal(result.summary,'Lead summary');cleanup();});
test('Owner Assistant refuses public lead repository',async()=>{const repo=setLeadEnv();let issueRead=false;globalThis.fetch=async(url)=>{const s=String(url);if(s===`https://api.github.com/repos/${repo}`)return new Response(JSON.stringify({private:false}),{status:200});issueRead=true;return new Response(JSON.stringify(SAMPLE_ISSUES),{status:200});};const result=await handleAssistantAction({action:'leads_summary'},fakeClient());assert.equal(result.ok,false);assert.equal(result.error,'unsafe_lead_repository');assert.equal(issueRead,false);cleanup();});
test('draft_reply returns a draft and explicitly does not send',async()=>{const repo=setLeadEnv();globalThis.fetch=privateRepoFetch(repo);const result=await handleAssistantAction({action:'draft_reply',issue_number:12},fakeClient('Draft reply'));assert.equal(result.ok,true);assert.equal(result.draft,'Draft reply');assert.match(result.note,/nothing has been sent/i);cleanup();});
test('ownerToday returns the local calendar date in the configured timezone',()=>{const utc=new Date().toISOString().slice(0,10).replace(/-/g,''),ny=ownerToday('America/New_York');assert.match(ny,/^\d{8}$/);const kiritimati=ownerToday('Pacific/Kiritimati');assert.ok(kiritimati>=utc||Number(kiritimati)>=Number(ny));});
test('today action surfaces a lead-tracker error instead of reporting no bookings',async()=>{const repo=setLeadEnv();globalThis.fetch=async(url)=>String(url)===`https://api.github.com/repos/${repo}`?new Response('{"message":"Bad credentials"}',{status:401}):new Response('[]',{status:200});const result=await handleAssistantAction({action:'today'},fakeClient('unused'));assert.equal(result.ok,false);assert.match(result.error,/lead_tracker_error/);assert.match(result.note,/may be hidden/i);cleanup();});
test('today lists booking requests and parses today calendar events in owner timezone',async()=>{const repo=setLeadEnv();process.env.CALENDAR_TIMEZONE='America/New_York';process.env.GOOGLE_CALENDAR_ICS_URL='https://calendar.google.com/private.ics';const today=ownerToday(process.env.CALENDAR_TIMEZONE),calendarText=`BEGIN:VCALENDAR\nBEGIN:VEVENT\nDTSTART:${today}T1400\nSUMMARY:Fit review call\nEND:VEVENT\nBEGIN:VEVENT\nDTSTART:19990101T1000\nSUMMARY:Old event\nEND:VEVENT\nEND:VCALENDAR`;globalThis.fetch=privateRepoFetch(repo,{calendarText});const{booking_requests,calendar_events}=await fetchTodaysBookings();assert.equal(booking_requests.length,1);assert.match(booking_requests[0].title,/^\[Booking\]/);assert.equal(calendar_events.length,1);assert.equal(calendar_events[0].summary,'Fit review call');assert.equal(calendar_events[0].time,'14:00');cleanup();});