import { test, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import netlifyHandler from '../netlify/functions/capture-lead.mjs';
import vercelHandler from '../api/capture-lead.mjs';

const SAMPLE_LEAD={
  'form-name':'ai-readiness-lead',name:'Test Lead',email:'test-lead@example.com',phone:'555-0100',path:'AI Starter Pass',audience_type:'Me as a job seeker',timeline:'This month',budget_range:'$59 starter pass',readiness_score:'64',score_summary:'Score 64/100 | Practical builder | Lead tier: Audit-ready lead',recommended_path:'Business AI Readiness Audit',lead_tier:'Audit-ready lead',lead_source:'utm-test',landing_page:'https://aikollege.com/',referrer:'direct',utm_source:'utm-test',message:'I need AI job proof.'
};
const realFetch=globalThis.fetch;let fetchCalls;
function mockFetch(responder){fetchCalls=[];globalThis.fetch=async(url,options={})=>{fetchCalls.push({url:String(url),options});return responder(String(url),options,fetchCalls.length);};}
function jsonResponse(value,status=200){return new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}});}
function githubIssueOk(){return jsonResponse({html_url:'https://github.com/x/y/issues/1',number:1},201);}
function privateRepoOk(){return jsonResponse({private:true,full_name:'owner/repo'},200);}
function standardGithubResponder(url){if(url==='https://api.github.com/repos/owner/repo')return privateRepoOk();return githubIssueOk();}
let ipCounter=0;function nextIp(){return `10.0.0.${ipCounter++}`;}
function netlifyRequest(data,method='POST',ip=nextIp()){return new Request('http://localhost/.netlify/functions/capture-lead',{method,headers:{'content-type':'application/json','x-forwarded-for':ip},body:method==='POST'?JSON.stringify(data):undefined});}
function vercelReqRes(data,method='POST',ip=nextIp()){const req={method,headers:{'content-type':'application/json','x-forwarded-for':ip},body:data};const res={statusCode:200,payload:undefined,status(code){this.statusCode=code;return this;},json(obj){this.payload=obj;return this;}};return{req,res};}
beforeEach(()=>{process.env.LEADS_SECRET='test-secret';process.env.LEADS_REPO=`owner/repo-${ipCounter++}`;});
afterEach(()=>{globalThis.fetch=realFetch;delete process.env.LEADS_SECRET;delete process.env.LEADS_REPO;});
function repoMetaUrl(){return `https://api.github.com/repos/${process.env.LEADS_REPO}`;}
function responderWithPrivateRepo(postResponder=()=>githubIssueOk()){return(url,options,callCount)=>{if(url===repoMetaUrl())return jsonResponse({private:true,full_name:process.env.LEADS_REPO});return postResponder(url,options,callCount);};}
function issuePosts(){return fetchCalls.filter(c=>(c.options.method||'GET').toUpperCase()==='POST');}

test('netlify: rejects non-POST requests',async()=>{const response=await netlifyHandler(netlifyRequest(null,'GET'));assert.equal(response.status,405);});
test('netlify: rejects missing name/email so the client falls back to email',async()=>{const response=await netlifyHandler(netlifyRequest({name:'',email:'not-an-email'}));assert.equal(response.status,400);assert.equal((await response.json()).ok,false);});
test('netlify: silently accepts honeypot submissions without creating an issue',async()=>{mockFetch(responderWithPrivateRepo());const response=await netlifyHandler(netlifyRequest({...SAMPLE_LEAD,_gotcha:'bot'}));const body=await response.json();assert.equal(body.ok,true);assert.equal(body.ignored,true);assert.equal(fetchCalls.length,0);});
test('netlify: signals email fallback when tracker is not configured',async()=>{delete process.env.LEADS_SECRET;const response=await netlifyHandler(netlifyRequest(SAMPLE_LEAD));assert.equal(response.status,503);const body=await response.json();assert.equal(body.ok,false);assert.equal(body.fallback,'email_form');});
test('netlify: refuses a public lead repository and falls back without writing PII',async()=>{mockFetch((url)=>url===repoMetaUrl()?jsonResponse({private:false,full_name:process.env.LEADS_REPO}):githubIssueOk());const response=await netlifyHandler(netlifyRequest(SAMPLE_LEAD));const body=await response.json();assert.equal(response.status,503);assert.equal(body.error,'unsafe_lead_repository');assert.equal(body.fallback,'email_form');assert.equal(issuePosts().length,0);});
test('netlify: creates a private GitHub issue carrying qualification and source data',async()=>{mockFetch(responderWithPrivateRepo());const response=await netlifyHandler(netlifyRequest(SAMPLE_LEAD));const body=await response.json();assert.equal(body.ok,true);assert.equal(body.issue_number,1);const posts=issuePosts();assert.equal(posts.length,1);const posted=JSON.parse(posts[0].options.body);assert.match(posted.title,/^\[Lead\] Test Lead/);for(const field of ['Readiness score: 64','Selected path: AI Starter Pass','Lead tier: Audit-ready lead','UTM source: utm-test','Budget range: $59 starter pass','Private customer record'])assert.ok(posted.body.includes(field),`issue body missing: ${field}`);assert.ok(posted.labels.includes('lead'));});
test('netlify: retries without labels when labels fail, so no lead is lost',async()=>{let postCount=0;mockFetch(responderWithPrivateRepo(()=>{postCount++;return postCount===1?jsonResponse({message:'Validation Failed'},422):githubIssueOk();}));const response=await netlifyHandler(netlifyRequest(SAMPLE_LEAD));assert.equal((await response.json()).ok,true);const posts=issuePosts();assert.equal(posts.length,2);assert.equal(JSON.parse(posts[1].options.body).labels,undefined);});
test('netlify: signals email fallback when GitHub privacy check is unavailable',async()=>{mockFetch((url)=>url===repoMetaUrl()?jsonResponse({message:'boom'},500):githubIssueOk());const response=await netlifyHandler(netlifyRequest(SAMPLE_LEAD));const body=await response.json();assert.equal(body.ok,false);assert.equal(body.fallback,'email_form');assert.equal(issuePosts().length,0);});
test('netlify: booking requests get the [Booking] title prefix',async()=>{mockFetch(responderWithPrivateRepo());await netlifyHandler(netlifyRequest({...SAMPLE_LEAD,request_type:'Booking request'}));const posted=JSON.parse(issuePosts()[0].options.body);assert.match(posted.title,/^\[Booking\]/);});
test('vercel: rejects non-POST requests',async()=>{const{req,res}=vercelReqRes(null,'GET');await vercelHandler(req,res);assert.equal(res.statusCode,405);});
test('vercel: creates the same private issue record as the netlify path',async()=>{mockFetch(responderWithPrivateRepo());const{req,res}=vercelReqRes(SAMPLE_LEAD);await vercelHandler(req,res);assert.equal(res.payload.ok,true);const posted=JSON.parse(issuePosts()[0].options.body);assert.ok(posted.body.includes('Lead tier: Audit-ready lead'));assert.ok(posted.body.includes('Private customer record'));});
test('vercel: signals email fallback when tracker is not configured',async()=>{delete process.env.LEADS_SECRET;const{req,res}=vercelReqRes(SAMPLE_LEAD);await vercelHandler(req,res);assert.equal(res.statusCode,503);assert.equal(res.payload.fallback,'email_form');});
test('netlify: throttles repeated posts from one IP and points them at email fallback',async()=>{mockFetch(responderWithPrivateRepo());const ip='203.0.113.7';let throttledStatus=0,throttledBody;for(let i=0;i<8;i++){const response=await netlifyHandler(netlifyRequest(SAMPLE_LEAD,'POST',ip));if(response.status===429){throttledStatus=429;throttledBody=await response.json();break;}}assert.equal(throttledStatus,429);assert.equal(throttledBody.fallback,'email_form');});