import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultOwnerSettings,sanitizeOwnerSettings,isWithinBusinessHours,loadOwnerSettings,saveOwnerSettings} from '../lib/owner-settings.mjs';
import {updateLeadWorkflow,handleAssistantAction} from '../lib/assistant-core.mjs';
const realFetch=globalThis.fetch;
function cleanup(){globalThis.fetch=realFetch;for(const k of ['LEADS_SECRET','LEADS_REPO','TWILIO_HUMAN_FORWARD_NUMBER','OWNER_ASSISTANT_TOKEN','ANTHROPIC_API_KEY'])delete process.env[k];}

test('owner settings validate risky fields and retain safe defaults',()=>{const d=defaultOwnerSettings(),s=sanitizeOwnerSettings({customerTone:'friendly',bookingUrl:'javascript:bad',humanForward:{enabled:true,number:'5551234567'},assistantAutonomy:'unlimited'},d);assert.equal(s.customerTone,'friendly');assert.equal(s.bookingUrl,d.bookingUrl);assert.equal(s.humanForward.enabled,false);assert.equal(s.assistantAutonomy,'draft');cleanup();});
test('owner settings accept E164 forwarding and HTTPS booking URL',()=>{const s=sanitizeOwnerSettings({bookingUrl:'https://www.aikollege.com/booking.html',humanForward:{enabled:true,number:'+15551234567',outsideHoursOnly:true},assistantAutonomy:'act-safe'});assert.equal(s.humanForward.enabled,true);assert.equal(s.humanForward.number,'+15551234567');assert.equal(s.humanForward.outsideHoursOnly,true);assert.equal(s.assistantAutonomy,'act-safe');cleanup();});
test('business hours evaluate in configured timezone',()=>{const s=defaultOwnerSettings();s.businessHours={enabled:true,timezone:'America/New_York',days:[1],start:'09:00',end:'17:00'};assert.equal(isWithinBusinessHours(s,new Date('2026-08-17T14:00:00Z')),true);assert.equal(isWithinBusinessHours(s,new Date('2026-08-17T23:00:00Z')),false);cleanup();});
test('settings refuse persistence without private store',async()=>{cleanup();const loaded=await loadOwnerSettings();assert.equal(loaded.persisted,false);const saved=await saveOwnerSettings({customerTone:'formal'});assert.equal(saved.ok,false);assert.equal(saved.error,'leads_not_configured');cleanup();});
test('settings persist only to verified private repository',async()=>{process.env.LEADS_SECRET='tok';process.env.LEADS_REPO='x/private';let stored=null;globalThis.fetch=async(url,options={})=>{const s=String(url);if(s==='https://api.github.com/repos/x/private')return new Response(JSON.stringify({private:true}),{status:200});if(options.method==='PUT'){stored=JSON.parse(options.body);return new Response(JSON.stringify({content:{sha:'new'}}),{status:201});}return new Response('',{status:404});};const out=await saveOwnerSettings({customerTone:'formal',humanForward:{enabled:true,number:'+15551234567'}});assert.equal(out.ok,true);assert.equal(out.settings.customerTone,'formal');assert.ok(stored.content);cleanup();});
test('lead lifecycle update preserves record and closes won/lost/closed',async()=>{process.env.LEADS_SECRET='tok';process.env.LEADS_REPO='x/private-life';let patch=null;globalThis.fetch=async(url,options={})=>{const s=String(url);if(s==='https://api.github.com/repos/x/private-life')return new Response(JSON.stringify({private:true}),{status:200});if(s.endsWith('/issues/12')&&options.method==='PATCH'){patch=JSON.parse(options.body);return new Response(JSON.stringify({html_url:'https://github.com/x/private-life/issues/12',title:'Lead'}),{status:200});}if(s.endsWith('/issues/12'))return new Response(JSON.stringify({number:12,title:'Lead',html_url:'https://github.com/x/private-life/issues/12',body:'Original customer data',labels:[]}),{status:200});return new Response('[]',{status:200});};const out=await updateLeadWorkflow({issue_number:12,status:'won',next_action:'Send onboarding',note:'Paid'});assert.equal(out.ok,true);assert.equal(out.workflow.status,'won');assert.equal(patch.state,'closed');assert.match(patch.body,/Original customer data/);assert.match(patch.body,/Status: won/);cleanup();});
test('pipeline health exposes control readiness without secrets',async()=>{process.env.LEADS_SECRET='tok';process.env.LEADS_REPO='x/private-health';process.env.OWNER_ASSISTANT_TOKEN='owner';process.env.ANTHROPIC_API_KEY='sk';globalThis.fetch=async(url)=>{const s=String(url);if(s==='https://api.github.com/repos/x/private-health')return new Response(JSON.stringify({private:true}),{status:200});return new Response('',{status:404});};const out=await handleAssistantAction({action:'pipeline_health'});assert.equal(out.ok,true);assert.equal(out.checks.lead_store,'private and reachable');assert.ok('human_forward' in out.checks);assert.doesNotMatch(JSON.stringify(out),/OWNER_ASSISTANT_TOKEN|LEADS_SECRET/);cleanup();});
