import test from 'node:test';
import assert from 'node:assert/strict';
import {SOCIAL_PLATFORMS,contentFingerprint,makeIdempotencyKey,sanitizeDraft,canTransition,transitionSocialOp,assertActorPermission,platformReadiness,publicationGate,socialCapabilities} from '../lib/social-ops.mjs';

test('four social platforms are first-class and stable',()=>{assert.deepEqual(SOCIAL_PLATFORMS,['facebook','instagram','linkedin','tiktok']);});
test('same content and campaign yields stable idempotency',()=>{const d1=sanitizeDraft({campaign_id:'launch',content_id:'a',platforms:['facebook','instagram'],text:'Hello world'},'owner'),d2=sanitizeDraft({campaign_id:'launch',content_id:'a',platforms:['instagram','facebook'],text:'Hello   world'},'owner');assert.equal(d1.fingerprint,d2.fingerprint);assert.equal(d1.idempotency_key,d2.idempotency_key);});
test('customer systems cannot create, approve, schedule or publish marketing',()=>{for(const actor of ['secretary','receptionist'])for(const action of ['create_draft','approve','schedule','publish','cancel'])assert.throws(()=>assertActorPermission(actor,action));assert.doesNotThrow(()=>assertActorPermission('secretary','status'));});
test('MoMo can propose and execute an approved publish but cannot self-approve or schedule',()=>{assert.doesNotThrow(()=>assertActorPermission('momo','create_draft'));assert.doesNotThrow(()=>assertActorPermission('momo','publish'));assert.throws(()=>assertActorPermission('momo','approve'));assert.throws(()=>assertActorPermission('momo','schedule'));});
test('MoMo cannot move an unapproved draft into publishing',()=>{const op=sanitizeDraft({platforms:['linkedin'],text:'Draft only'},'momo');assert.equal(canTransition('draft','publishing','momo'),false);assert.throws(()=>transitionSocialOp(op,'publishing',{actor:'momo'}));});
test('owner approval binds content fingerprint and then MoMo may enter publishing',()=>{let op=sanitizeDraft({platforms:['linkedin'],text:'Useful educational post'},'momo');op=transitionSocialOp(op,'review',{actor:'momo'});assert.equal(canTransition('review','approved','momo'),false);op=transitionSocialOp(op,'approved',{actor:'owner'});assert.equal(op.approval.actor,'owner');assert.equal(op.approval.fingerprint,op.fingerprint);const publishing=transitionSocialOp(op,'publishing',{actor:'momo'});assert.equal(publishing.state,'publishing');});
test('published and cancelled records cannot be silently mutated',()=>{assert.equal(canTransition('published','review','owner'),false);assert.equal(canTransition('cancelled','review','owner'),false);});
test('publication gate is fail closed without explicit switch and credentials',()=>{let op=sanitizeDraft({platforms:['facebook','tiktok'],text:'Test'},'owner');op=transitionSocialOp(op,'review',{actor:'owner'});op=transitionSocialOp(op,'approved',{actor:'owner'});assert.equal(publicationGate(op,{}).error,'publishing_disabled');assert.equal(publicationGate(op,{SOCIAL_PUBLISH_ENABLED:'true'}).error,'platform_not_configured');});
test('platform readiness uses independent account credentials',()=>{const r=platformReadiness({META_ACCESS_TOKEN:'m',META_PAGE_ID:'p',INSTAGRAM_BUSINESS_ACCOUNT_ID:'i',LINKEDIN_ACCESS_TOKEN:'l',LINKEDIN_AUTHOR_URN:'urn:li:organization:1',TIKTOK_ACCESS_TOKEN:'t',TIKTOK_OPEN_ID:'o'});assert.equal(r.facebook.configured,true);assert.equal(r.instagram.configured,true);assert.equal(r.linkedin.configured,true);assert.equal(r.tiktok.configured,true);});
test('capabilities make authority boundaries explicit',()=>{const c=socialCapabilities({});assert.deepEqual(c.approval_authority,['owner']);assert.equal(c.momo_can_self_approve,false);assert.match(c.publish_execution_authority.join(','),/momo-after-owner-approval/);assert.equal(c.customer_system_marketing_publish,false);assert.equal(c.destructive_remote_actions,false);});
