import { test, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {verifySignature,handleVerificationRequest,extractMessages,isOwnerNumber,routeMessage,isWhatsAppConfigured} from '../lib/whatsapp-core.mjs';
const realFetch=globalThis.fetch;beforeEach(()=>{process.env.WHATSAPP_APP_SECRET='app-secret';process.env.WHATSAPP_VERIFY_TOKEN='verify-me';});afterEach(()=>{globalThis.fetch=realFetch;for(const key of ['WHATSAPP_APP_SECRET','WHATSAPP_VERIFY_TOKEN','WHATSAPP_TOKEN','WHATSAPP_PHONE_NUMBER_ID','OWNER_WHATSAPP_NUMBER','OWNER_ASSISTANT_TOKEN','ANTHROPIC_API_KEY','LEADS_SECRET','LEADS_REPO'])delete process.env[key];});
function sign(body){return'sha256='+crypto.createHmac('sha256','app-secret').update(body).digest('hex');}
test('signature verification accepts a valid Meta signature and rejects tampering',()=>{const body=JSON.stringify({hello:'world'});assert.equal(verifySignature(body,sign(body)),true);assert.equal(verifySignature(body+' ',sign(body)),false);assert.equal(verifySignature(body,'sha256=deadbeef'),false);assert.equal(verifySignature(body,undefined),false);});
test('GET verification handshake echoes the challenge only with the right token',()=>{const good=new URLSearchParams({'hub.mode':'subscribe','hub.verify_token':'verify-me','hub.challenge':'12345'});assert.deepEqual(handleVerificationRequest(good),{ok:true,challenge:'12345'});const bad=new URLSearchParams({'hub.mode':'subscribe','hub.verify_token':'wrong','hub.challenge':'12345'});assert.equal(handleVerificationRequest(bad).ok,false);});
test('extractMessages pulls text messages and ignores other types',()=>{const payload={entry:[{changes:[{value:{messages:[{type:'text',from:'15551230000',id:'wamid.1',text:{body:'Hi there'}},{type:'image',from:'15551230000',id:'wamid.2'}]}}]}]};const messages=extractMessages(payload);assert.equal(messages.length,1);assert.equal(messages[0].text,'Hi there');});
test('owner number matching normalizes formats',()=>{process.env.OWNER_WHATSAPP_NUMBER='+1 (555) 123-0000';assert.equal(isOwnerNumber('15551230000'),true);assert.equal(isOwnerNumber('15550000000'),false);delete process.env.OWNER_WHATSAPP_NUMBER;assert.equal(isOwnerNumber('15551230000'),false);});
test('customer messages use private settings/memory, route to secretary and save handoff',async()=>{process.env.LEADS_SECRET='t';process.env.LEADS_REPO='x/private-leads';let loggedIssue=null,memoryPut=0;globalThis.fetch=async(url,options={})=>{const s=String(url),method=(options.method||'GET').toUpperCase();if(s==='https://api.github.com/repos/x/private-leads')return new Response(JSON.stringify({private:true}),{status:200});if(s.includes('/contents/.ai-kollege-owner-settings.json'))return new Response('',{status:404});if(s.includes('/contents/.ai-kollege-conversations/')){if(method==='PUT'){memoryPut++;return new Response(JSON.stringify({content:{sha:'memory'}}),{status:201});}return new Response('',{status:404});}if(s.endsWith('/issues')&&method==='POST'){loggedIssue=JSON.parse(options.body);return new Response(JSON.stringify({html_url:'https://github.com/x/private-leads/issues/7',number:7}),{status:201});}return new Response('{}',{status:200});};const client={messages:{create:async()=>({stop_reason:'end_turn',content:[{type:'text',text:JSON.stringify({reply:'A refund needs a human decision — one will follow up.',handoff:true,offer_booking:true,lead:{name:null,email:null,need:'refund',path:null}})}]})}};const result=await routeMessage({from:'+1 (555) 999-8888',text:'I want a refund now',client});assert.equal(result.routed,'secretary');assert.equal(result.handoff,true);assert.match(result.reply,/Booking & review:/);assert.ok(memoryPut>=1);assert.ok(loggedIssue.body.includes('Channel: whatsapp'));assert.ok(loggedIssue.body.includes('15559998888'));assert.ok(loggedIssue.body.includes('Private customer record'));assert.doesNotMatch(loggedIssue.title,/15559998888/);});
test('WhatsApp booking fallback uses canonical www domain',async()=>{const client={messages:{create:async()=>({stop_reason:'end_turn',content:[{type:'text',text:JSON.stringify({reply:'Please book a review.',handoff:false,offer_booking:true,lead:null})}]})}};const result=await routeMessage({from:'15554443333',text:'how do I book?',client});assert.match(result.reply,/https:\/\/www\.aikollege\.com\/booking\.html/);});
test('owner route is refused when private assistant is not enabled',async()=>{process.env.OWNER_WHATSAPP_NUMBER='15551230000';const result=await routeMessage({from:'15551230000',text:'leads'});assert.equal(result.routed,'owner_unconfigured');});
test('per-sender rate limiting kicks in',async()=>{const client={messages:{create:async()=>({stop_reason:'end_turn',content:[{type:'text',text:JSON.stringify({reply:'ok',handoff:false,offer_booking:false,lead:null})}]})}};let limited=false;for(let i=0;i<12;i++){const result=await routeMessage({from:'15557776666',text:`msg ${i}`,client});if(result.routed==='rate_limited'){limited=true;break;}}assert.equal(limited,true);});
test('whatsapp is only configured when every secret is present',()=>{assert.equal(isWhatsAppConfigured(),false);process.env.WHATSAPP_TOKEN='t';process.env.WHATSAPP_PHONE_NUMBER_ID='p';process.env.ANTHROPIC_API_KEY='sk';assert.equal(isWhatsAppConfigured(),true);});
