import crypto from 'node:crypto';
import {privateStoreGate} from './owner-settings.mjs';
const DIR='.ai-kollege-conversations';
function headers(){const h={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'ai-kollege-channel-memory','Content-Type':'application/json'};h[['Author','ization'].join('')]=`Bearer ${process.env.LEADS_SECRET||''}`;return h;}
function idFor(channel,contact){return crypto.createHash('sha256').update(`${channel}:${contact}`).digest('hex').slice(0,32);}
function deriveKey(secret){return crypto.createHash('sha256').update(`aik-memory:${secret||''}`).digest();}
function keyCandidates(){const primary=process.env.CHANNEL_MEMORY_KEY||process.env.LEADS_SECRET||'',legacy=process.env.CHANNEL_MEMORY_LEGACY_KEY||'';const list=[primary,legacy].filter(Boolean).map(deriveKey);return [...new Map(list.map(k=>[k.toString('hex'),k])).values()];}
export function memoryKeySource(){return process.env.CHANNEL_MEMORY_KEY?'dedicated':process.env.LEADS_SECRET?'legacy-leads-secret':'unconfigured';}
function encrypt(history){const key=keyCandidates()[0];if(!key)throw new Error('memory_key_unconfigured');const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),plain=Buffer.from(JSON.stringify(history)),enc=Buffer.concat([cipher.update(plain),cipher.final()]),tag=cipher.getAuthTag();return Buffer.concat([iv,tag,enc]).toString('base64');}
function decryptWith(raw,key){const iv=raw.subarray(0,12),tag=raw.subarray(12,28),enc=raw.subarray(28),d=crypto.createDecipheriv('aes-256-gcm',key,iv);d.setAuthTag(tag);return JSON.parse(Buffer.concat([d.update(enc),d.final()]).toString('utf8'));}
function decrypt(value){try{const raw=Buffer.from(String(value||''),'base64');if(raw.length<29)return[];for(const key of keyCandidates()){try{const data=decryptWith(raw,key);return(Array.isArray(data)?data:[]).slice(-8).map(t=>({role:t.role==='assistant'?'assistant':'user',text:String(t.text||'').slice(0,1200)}));}catch{}}return[];}catch{return[];}}
function pathFor(channel,contact){return `${DIR}/${idFor(channel,contact)}.json`;}
export async function loadChannelHistory(channel,contact){const gate=await privateStoreGate();if(!gate.ok)return{history:[],persisted:false,error:gate.error};const path=pathFor(channel,contact),r=await fetch(`https://api.github.com/repos/${gate.repo}/contents/${path}`,{headers:headers()});if(r.status===404)return{history:[],persisted:false,error:null};if(!r.ok)return{history:[],persisted:false,error:`memory_read_${r.status}`};try{const data=await r.json(),doc=JSON.parse(Buffer.from(data.content||'','base64').toString('utf8'));return{history:decrypt(doc.ciphertext),persisted:true,sha:data.sha,error:null};}catch{return{history:[],persisted:false,error:'memory_invalid'};}}
export async function saveChannelHistory(channel,contact,history=[]){const gate=await privateStoreGate();if(!gate.ok)return{ok:false,error:gate.error};if(!keyCandidates().length)return{ok:false,error:'memory_key_unconfigured'};const current=await loadChannelHistory(channel,contact),path=pathFor(channel,contact),safe=(Array.isArray(history)?history:[]).slice(-8).map(t=>({role:t.role==='assistant'?'assistant':'user',text:String(t.text||'').replace(/[\u0000-\u001f\u007f]/g,' ').slice(0,1200)})),doc={version:2,key_source:memoryKeySource(),updated_at:new Date().toISOString(),ciphertext:encrypt(safe)},body={message:`Update ${channel} receptionist conversation state`,content:Buffer.from(JSON.stringify(doc,null,2)+'\n').toString('base64')};if(current.sha)body.sha=current.sha;const r=await fetch(`https://api.github.com/repos/${gate.repo}/contents/${path}`,{method:'PUT',headers:headers(),body:JSON.stringify(body)});return r.ok?{ok:true}:{ok:false,error:`memory_write_${r.status}`};}
