import crypto from 'node:crypto';
import {privateStoreGate} from './owner-settings.mjs';

const MAX_IDS=256;
const local=new Map();
function cleanNamespace(v){return String(v||'webhook').toLowerCase().replace(/[^a-z0-9_-]/g,'').slice(0,32)||'webhook';}
function digest(v){return crypto.createHash('sha256').update(String(v||'')).digest('hex');}
function headers(){const h={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'ai-kollege-webhook-replay','Content-Type':'application/json'};h[['Author','ization'].join('')]=`Bearer ${process.env.LEADS_SECRET||''}`;return h;}
function pathFor(namespace){return `.ai-kollege-replay-${cleanNamespace(namespace)}.json`;}
function pruneLocal(now=Date.now()){for(const[k,t]of local)if(now-t>86400000)local.delete(k);}
async function readDoc(repo,path){const r=await fetch(`https://api.github.com/repos/${repo}/contents/${encodeURIComponent(path)}`,{headers:headers()});if(r.status===404)return{ids:[],sha:null};if(!r.ok)throw new Error(`replay_read_${r.status}`);const d=await r.json(),parsed=JSON.parse(Buffer.from(d.content||'','base64').toString('utf8'));return{ids:Array.isArray(parsed.ids)?parsed.ids.slice(-MAX_IDS):[],sha:d.sha||null};}
async function writeDoc(repo,path,ids,sha){const body={message:'Update AI Kollege webhook replay guard',content:Buffer.from(JSON.stringify({version:1,updated_at:new Date().toISOString(),ids:ids.slice(-MAX_IDS)},null,2)+'\n').toString('base64')};if(sha)body.sha=sha;return fetch(`https://api.github.com/repos/${repo}/contents/${encodeURIComponent(path)}`,{method:'PUT',headers:headers(),body:JSON.stringify(body)});}
export async function reserveWebhookEvent(namespace,eventId){const raw=String(eventId||'').trim();if(!raw)return{ok:false,error:'event_id_required'};const ns=cleanNamespace(namespace),id=digest(`${ns}:${raw}`),localKey=`${ns}:${id}`,now=Date.now();pruneLocal(now);if(local.has(localKey))return{ok:true,duplicate:true,persisted:false};const gate=await privateStoreGate();if(!gate.ok){local.set(localKey,now);return{ok:true,duplicate:false,persisted:false,warning:gate.error};}const path=pathFor(ns);try{for(let attempt=0;attempt<2;attempt++){const current=await readDoc(gate.repo,path);if(current.ids.includes(id)){local.set(localKey,now);return{ok:true,duplicate:true,persisted:true};}const r=await writeDoc(gate.repo,path,[...current.ids,id],current.sha);if(r.ok){local.set(localKey,now);return{ok:true,duplicate:false,persisted:true};}if(![409,422].includes(r.status))throw new Error(`replay_write_${r.status}`);}local.set(localKey,now);return{ok:true,duplicate:false,persisted:false,warning:'replay_conflict'};}catch(e){local.set(localKey,now);return{ok:true,duplicate:false,persisted:false,warning:String(e?.message||'replay_store_unavailable')};}}
