// WhatsApp Business Cloud API bridge. Owner messages route to private Owner Studio;
// customer messages use the same safe receptionist logic as web/phone.
import crypto from 'node:crypto';
import { runSecretary, logConversationLead, rateLimit, suggestPublicLinks } from './secretary-core.mjs';
import { handleAssistantAction } from './assistant-core.mjs';
import {loadOwnerSettings} from './owner-settings.mjs';
import {loadChannelHistory,saveChannelHistory} from './channel-memory.mjs';

export function isWhatsAppConfigured(){return Boolean(process.env.WHATSAPP_VERIFY_TOKEN&&process.env.WHATSAPP_APP_SECRET&&process.env.WHATSAPP_TOKEN&&process.env.WHATSAPP_PHONE_NUMBER_ID&&process.env.ANTHROPIC_API_KEY);}
export function verifySignature(rawBody,signatureHeader){const secret=process.env.WHATSAPP_APP_SECRET||'';if(!secret||!signatureHeader)return false;const expected='sha256='+crypto.createHmac('sha256',secret).update(rawBody).digest('hex'),a=Buffer.from(expected),b=Buffer.from(String(signatureHeader));return a.length===b.length&&crypto.timingSafeEqual(a,b);}
export function handleVerificationRequest(params){if(params.get('hub.mode')==='subscribe'&&params.get('hub.verify_token')===(process.env.WHATSAPP_VERIFY_TOKEN||'__unset__'))return{ok:true,challenge:params.get('hub.challenge')||''};return{ok:false};}
export function extractMessages(payload){const messages=[];for(const entry of payload?.entry||[])for(const change of entry.changes||[])for(const msg of change.value?.messages||[]){if(msg.type!=='text'||!msg.text?.body)continue;messages.push({from:msg.from,text:String(msg.text.body).slice(0,2000),id:msg.id});}return messages;}
export async function sendWhatsAppReply(to,text){const response=await fetch(`https://graph.facebook.com/v21.0/${process.env.WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:'POST',headers:{'Content-Type':'application/json',[['Author','ization'].join('')]:`Bearer ${process.env.WHATSAPP_TOKEN}`},body:JSON.stringify({messaging_product:'whatsapp',to,type:'text',text:{body:String(text).slice(0,4000)}})});return response.ok;}
function normalizeNumber(value){return String(value||'').replace(/[^0-9]/g,'');}
export function isOwnerNumber(from){const owner=normalizeNumber(process.env.OWNER_WHATSAPP_NUMBER);return Boolean(owner)&&normalizeNumber(from)===owner;}
async function ownerReply(text,client){const lower=text.trim().toLowerCase();let result;if(lower==='leads'||lower==='lead summary'){result=await handleAssistantAction({action:'leads_summary',limit:10},client);return result.ok?result.summary:`Assistant error: ${result.error}`;}if(lower==='today'||lower==='bookings'){result=await handleAssistantAction({action:'today'},client);if(!result.ok)return`Assistant error: ${result.error}`;const requests=result.booking_requests.map(b=>`• ${b.title} (${b.url})`).join('\n')||'No open booking requests.',events=result.calendar_events.map(e=>`• ${e.time} ${e.summary}`).join('\n')||'No calendar events today.';return`Booking requests:\n${requests}\n\nToday's calendar:\n${events}`;}if(lower==='settings'||lower==='front office settings'){result=await handleAssistantAction({action:'get_settings'},client);return result.ok?`Front office settings (${result.fingerprint}):\nSecretary: ${result.settings.secretaryEnabled?'on':'off'}\nWeb: ${result.settings.webSecretaryEnabled?'on':'off'}\nWhatsApp customers: ${result.settings.whatsappCustomerEnabled?'on':'off'}\nHuman forward: ${result.settings.humanForward.enabled?'on':'off'}\nTone: ${result.settings.customerTone}`:`Assistant error: ${result.error}`;}const draftMatch=lower.match(/^draft\s+#?(\d+)/);if(draftMatch){result=await handleAssistantAction({action:'draft_reply',issue_number:Number(draftMatch[1])},client);return result.ok?`DRAFT (nothing sent):\n\n${result.draft}`:`Assistant error: ${result.error}`;}result=await handleAssistantAction({action:'ask',prompt:text},client);return result.ok?result.answer:`Assistant error: ${result.error}`;}
export async function routeMessage({from,text,client}={}){const normalized=normalizeNumber(from);if(!rateLimit(`wa:${normalized}`,{limit:8,windowMs:60000}))return{reply:'You are sending messages faster than I can safely answer. Please wait a minute and try again.',routed:'rate_limited'};if(isOwnerNumber(from)){if(!process.env.OWNER_ASSISTANT_TOKEN)return{reply:'Owner assistant is not configured yet.',routed:'owner_unconfigured'};return{reply:await ownerReply(text,client),routed:'assistant'};}
  const loaded=await loadOwnerSettings(),settings=loaded.settings;if(!settings.secretaryEnabled||!settings.whatsappCustomerEnabled)return{reply:'The AI receptionist is currently offline on WhatsApp. Please use https://www.aikollege.com/booking.html for human follow-up.',routed:'customer_disabled'};
  const memory=await loadChannelHistory('whatsapp',normalized),history=memory.history||[],result=await runSecretary({message:text,history,client,settings}),next=[...history,{role:'user',text},{role:'assistant',text:result.reply}].slice(-8);await saveChannelHistory('whatsapp',normalized,next).catch(()=>null);let logged=null;if(result.handoff||result.lead)logged=await logConversationLead({result,message:text,history,channel:'whatsapp',contact:normalized}).catch(()=>null);let reply=result.reply;const links=suggestPublicLinks(text+' '+result.reply,settings.recommendedLinks).slice(0,2);if(result.offer_booking&&!links.some(x=>x.key==='booking'))links.push({key:'booking',label:'Booking & review',href:'/booking.html'});for(const link of links.slice(0,2)){const href=link.key==='booking'?settings.bookingUrl:`https://www.aikollege.com${link.href}`;reply+=`\n\n${link.label}: ${href}`;}if(result.handoff)reply+=logged?.ok?'\n\nI saved this for human follow-up.':'\n\nI could not save the follow-up automatically; please use the booking page.';return{reply,routed:'secretary',handoff:result.handoff,memory_persisted:memory.persisted||false,followup_saved:Boolean(logged?.ok)};}
